# Generated by Django 5.1.2 on 2024-11-01 23:23

import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[doctor.utils.validate_sueldo], verbose_name='Sueldo'),
        ),
    ]
