# Generated by Django 5.1.2 on 2024-11-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='horario_atencion',
            field=models.JSONField(blank=True, default=dict, verbose_name='Horario de Atención'),
        ),
    ]
