# Generated by Django 5.1.2 on 2024-11-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medicamento_cantidad_alter_medicamento_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcamedicamento',
            options={'verbose_name': 'Marca de Medicamento', 'verbose_name_plural': 'Marca de Medicamentos'},
        ),
    ]
