# Generated by Django 5.1.2 on 2024-11-02 04:59

import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_marcamedicamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[doctor.utils.generate_valid_diagnosis_code], verbose_name='Código del Diagnóstico'),
        ),
    ]
