# Generated by Django 5.1.2 on 2024-11-05 10:57

import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosadicionales',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[doctor.utils.valida_numero_decimal_positivo], verbose_name='Costo del Servicio'),
        ),
    ]
